#!/bin/sh

# ip_address=$(curl --silent api.ipify.org)
# echo "🔰$ip_address"



  obs=`ps -e | rg -w obs`
  nobs=`ps -e | rg -w fasz`
  pubip=`wget http://ipecho.net/plain -O - -q ; echo`
    if [[ "$obs" == "$nobs" ]]
      then
        echo -e "🔰:$pubip"
    else
      echo -e "🔰:Classified"
  fi
