#!/usr/bin/env bash

case $BLOCK_BUTTON in
	1) setsid -f "$TERMINAL" -e neomutt ;;
	2) setsid -f mw -Y >/dev/null ;;
	3) notify-send "📬 Mail module" "\- Shows unread mail
- Shows 🔃 if syncing mail
- Left click opens neomutt
- Middle click syncs mail" ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

# unread="$(find "${XDG_DATA_HOME:-$HOME/.local/share}"/mail/*/[Ii][Nn][Bb][Oo][Xx]/new/* -type f 2>/dev/null | wc -l 2>/dev/null)"
# [ "$unread" != "0" ] && mpv --no-video --no-terminal ./email.recv.mp3 && notify-send "📬 温馨提示：您有($unread)封未读邮件"
# echo "📬:$unread(Mail)"



function email {
	declare -i new=$(du -a ~/.local/share/mail/*/INBOX/new/* 2>/dev/null | sed -n '$=')
	if [[ "$new" == 0 ]];then
    echo "📭:0(Mail)"
	else
    echo "📬:$new(Mail)"
    mpv --no-video --no-terminal ./email.recv.mp3 && notify-send "📬 温馨提示：您有($new)封未读邮件"
	fi
}

email
